"""
Performance benchmarking script
"""

# This file is part of the simulator_awgn_python distribution
# https://github.com/and-kirill/ldpc_soft_py/.
# Copyright (c) 2023 Kirill Andreev, Alexey Frolov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
 

import os
import sys

import numpy as np
if len(sys.argv) < 2 or sys.argv[1].lower() == 'ldpc':
    COMPILE_CMD_BASE = "g++         -O3 bench_impl.cpp bin_alist_loader"
elif sys.argv[1].lower() == 'gldpc':
    COMPILE_CMD_BASE = "g++ -DGLDPC -O3 bench_impl.cpp bin_alist_loader"
else:
    raise ValueError("Unknown command")
    

COMPILE_OLD = COMPILE_CMD_BASE + ".cpp"
COMPILE_NEW = COMPILE_CMD_BASE + "_fast.cpp -DNEW_IMPL -Wall"

OUTPUT_OLD = "old.txt"
OUTPUT_NEW = "new.txt"

EXEC_OLD = "old"
EXEC_NEW = "new"

VALGRIND_CMD = "valgrind"
PERF_PROFILER_CMD = VALGRIND_CMD + " --tool=callgrind"
CACHE_PROFILER_CMD = PERF_PROFILER_CMD + " --simulate-cache=yes"



def compile_cmd(is_old_impl, need_print=False):
    """
    Compile sources depending on config and return executable file
    """
    cmd = COMPILE_OLD if is_old_impl else COMPILE_NEW
    exec_file = EXEC_OLD if is_old_impl else EXEC_NEW
    cmd += f" -o {exec_file}"
    if need_print:
        cmd += " -DPRINT_OUTPUT"
    print(cmd)
    os.system(cmd)
    return exec_file


def gen_exec_cmd(is_old_impl, need_print=False):
    """
    Generate bash command to be executed
    """
    output_file = OUTPUT_OLD if is_old_impl else OUTPUT_NEW
    exec_file = compile_cmd(is_old_impl, need_print)
    # Running
    cmd = f"./{exec_file} > {output_file}"
    print(cmd)
    return cmd


def run_bench(is_old_impl, need_print=False):
    """
    Template for wallclock benchmarking
    """
    os.system(gen_exec_cmd(is_old_impl, need_print))


def run_profiler(is_old_impl, profiler_cmd):
    """
    Template for valgrind benchmarking
    """
    exec_file = compile_cmd(is_old_impl)
    cmd = profiler_cmd + " ./" + exec_file
    print("Target command:", cmd)
    if sys.platform == "darwin":
        print("Valgrind is not available for macOS")
    else:
        os.system(cmd)


def parse_output(txt_filename):
    """
    Parse wallclock execution time from text output generated by C++ bench tests
    """
    with open(txt_filename, "r", encoding="utf-8") as fhandle:
        data = fhandle.read()
    print(data)
    time_vals = [[], [], [], [], [], []]

    for s in data.splitlines():
        if s.startswith("Horizonral layered min sum: "):
            time_vals[0].append(float(s.split(" ")[4]))
        if s.startswith("Flooding min sum: "):
            time_vals[1].append(float(s.split(" ")[13]))
        if s.startswith("Flooding sum product: "):
            time_vals[2].append(float(s.split(" ")[9]))
        if s.startswith("Vertically layered min sum: "):
            time_vals[3].append(float(s.split(" ")[4]))
        if s.startswith("GLDPC Horiz. layered NOMS:"):
            time_vals[4].append(float(s.split(" ")[5]))
        if s.startswith("GLDPC flooding sum prod.:"):
            time_vals[5].append(float(s.split(" ")[6]))
    return time_vals


def diff_test():
    """
    Check diff between reference and updated implementation output
    """
    print("=" * 20, "Checking difference", "=" * 20)
    run_bench(is_old_impl=True, need_print=True)
    run_bench(is_old_impl=False, need_print=True)
    file_list = " " + OUTPUT_NEW + " " + OUTPUT_OLD
    os.system("diff" + file_list)
    os.system("ls -lh" + file_list)
    # os.system("rm" + file_list)

def print_ratio(msg, data_old, data_new):
    if not data_old:
        pass
    ratios = np.array(data_old) / np.array(data_new)
    print(msg, end="")
    for val in ratios:
        print(f"{val:1.4f} ", end="")
    print("")


def wallclock_test():
    """
    Evaluate wallclosck speedup ratio
    """
    print("=" * 20, "Benchmarking OLD", "=" * 20)
    run_bench(is_old_impl=True)
    time_vals_old = parse_output("old.txt")

    print("=" * 20, "Benchmarking NEW", "=" * 20)
    run_bench(is_old_impl=False)
    time_vals_new = parse_output(OUTPUT_NEW)
    msgs = {
        0: "HL    NOMS speedup: ",
        1: "FLOOD NOMS speedup: ",
        2: "FLOOD SPA  speedup: ",
        3: "VL    NOMS speedup: ",
        4: "GLDPC NOMS speedup: ",
        5: "GLDPC SPA  speedup: "
    }
    for i, msg in msgs.items():
        print_ratio(msg, time_vals_old[i], time_vals_new[i])

def profiler_test():
    """
    Run all valgrind tests
    """
    print("Valgrind: sanity check")
    run_profiler(is_old_impl=True, profiler_cmd=VALGRIND_CMD)
    run_profiler(is_old_impl=False, profiler_cmd=VALGRIND_CMD)

    print("Profiling cache:")
    run_profiler(is_old_impl=True, profiler_cmd=CACHE_PROFILER_CMD)
    run_profiler(is_old_impl=False, profiler_cmd=CACHE_PROFILER_CMD)

    print("Profiling performance:")
    run_profiler(is_old_impl=True, profiler_cmd=PERF_PROFILER_CMD)
    run_profiler(is_old_impl=False, profiler_cmd=PERF_PROFILER_CMD)


if __name__ == "__main__":
    diff_test()
    wallclock_test()
    profiler_test()
